mixed-port: 9696
# HTTP(S) 和 SOCKS 代理混合端口
redir-port: 9797
# 透明代理端口，用于 Linux 和 MacOS
tproxy-port: 9898
# 透明代理端口，可以代理 TCP 以及 UDP 流量，仅限 linux
mode: rule
# rule 规则匹配
# global 全局代理(需要在GLOBAL策略组选择代理/策略)
# direct 全局直连
find-process-mode: strict
# always 开启，强制匹配所有进程
# strict 默认，由 Clash 判断是否开启
# off 不匹配进程，推荐在路由器上使用此模式
global-client-fingerprint: chrome
# 全局客户端指纹，可选:
# "chrome", "firefox", "safari", "iOS", "android",
# "edge", "360"," qq", "random"
# 若选择 "random", 则按 Cloudflare Radar 数据
# 按概率生成一个现代浏览器指纹
log-level: warning
# 日志级别
# silent 静默，不输出
# error 仅输出发生错误至无法使用的日志
# warning 输出发生错误但不影响运行的日志以及 error 级别内容
# info 输出一般运行的内容,，及 error 和 warning 级别的日志
# debug 尽可能的输出运行中所有的信息
allow-lan: true
# 允许局域网内其他设备经过 Clash 的代理端口访问互联网
bind-address: "*"
# 绑定 IP,通过 LAN 访问一个/一些特定的 IP 地址
# "*" 绑定所有 IP 地址，不填写此项则绑定全部
# authentication:
  # - "user1:pass1"
  # - "user2:pass2"
  # http(s)/socks/mixed代理的用户验证
ipv6: false
# 是否允许内核接受 IPv6 流量，可选值 true/false
tcp-concurrent: true
# tcp并发，允许同时处理多个tcp连接，可选值 true/false
keep-alive-interval: 75
# TCP Keep Alive 间隔，单位秒钟
# 控制 Clash 发出 TCP Keep Alive 包的间隔
# 减少移动设备耗电问题的临时措施
unified-delay: true
# 统一延迟，去除握手等额外延迟，可选值 true/false

geodata-mode: true
# GeoIP 使用的文件，可选 true 为.dat / false 为.mmdb
geosite-matcher: succinct
# GeoSite 使用的匹配器实现，可选:
# succinct 与规则集相同 / mph 来自 V2Ray，也是 Xray 中的“混合”
geodata-loader: standard
# GEO 文件加载模式，可选:
# standard: 标准加载器
# memconservative: 专为内存受限(小内存)设备优化的加载器(默认值)
geo-auto-update: true
# 是否自动更新 GEO 文件，可选 true/false
geo-update-interval: 24
# 更新间隔，单位：小时
geox-url:
  # GEO 文件下载地址
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

external-ui: "/data/adb/box/clash"
# 外部用户界面路径，可以为绝对路径 或 Clash 工作目录的相对路径
external-ui-name: "zashboard"
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
global-ua: clash.meta
# 自定义外部资源下载时使用的UA，默认为 clash.meta
external-controller: 127.0.0.1:9090
# 外部控制器，你可以将 127.0.0.1 修改为 0.0.0.0 来监听所有 IP
secret: meta
# API 的访问密钥

# external-doh-server: /dns-query
# 在RESTful API端口上开启DOH服务器
# ！！！该URL不会验证secret， 如果开启请自行保证安全问题 ！！！

# 类似于 /etc/hosts, 仅支持配置单个 IP
# hosts:
# '*.mihomo.dev': 127.0.0.1
# '.dev': 127.0.0.1
# 'alpha.mihomo.dev': '::1'
# test.com: [1.1.1.1, 2.2.2.2]
# home.lan: lan # lan 为特别字段，将加入本地所有网卡的地址
# baidu.com: google.com # 只允许配置一个别名

profile:
  # 缓存
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  use-hosts: true
  use-system-hosts: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*'
    - '*.lan'
    - '*.local'
    - '10.*'
    - '172.16.*'
    - '192.168.*'
    - '*.bilibili.com'
    - '*.biliapi.net'
    - '*.mtalk.google.com'
    - 'alt*-mtalk.google.com'
  nameserver-policy:
  # 指定域名查询的解析服务器
  # 可使用 geosite, 优先于 nameserver/fallback 查询
  # 键支持域名通配，值支持字符串/数组
    '+.arpa': '10.0.0.1'
    'geosite:cn': 
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    '+.taobao.com': '223.5.5.5'
    '+.jd.com': '114.114.114.114'
    '+.baidu.com': '114.114.114.114'

  proxy-server-nameserver:
  #仅用于解析代理节点的域名
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  direct-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
  # 用于解析域名
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - 114.114.114.114
    - 223.5.5.5
  default-nameserver:
  # 用于解析 DNS 服务器 的域名，必须为 IP, 可为加密 DNS
    - 223.5.5.5
    - 114.114.114.114
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
    - 208.67.222.222
  fallback-filter:
    geoip: true #
    geoip-code: CN #
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.twitter.com'
      - '+.telegram.org'
      - '+.x.com'

health-check: &url
  url: https://www.gstatic.com/generate_204

q: &q
  interval: 600 # 健康检测间隔（秒）
  <<: *url
  timeout: 5000 # 健康检查超时时间（毫秒）
  lazy: true
  hidden: true

dy: &dy
  type: http
  interval: 86400
  # 每24小时更新
  health-check: 
    enable: true
    <<: *url
    interval: 300

proxy-providers:
  tsmeow:
    url: "订阅链接1"
    <<: *dy
    path: ./providers/tsmeow.yaml
    override:
      additional-prefix: "tsmeow | "
  jk:
    url: "订阅链接2"
    <<: *dy
    path: ./providers/jk.yaml
    override:
      additional-prefix: "jk | "
  zmdy:
    url: "订阅链接3"
    <<: *dy
    path: ./providers/zmdy.yaml
    override:
      additional-prefix: "zmdy | "
  # 代理提供商:
    # url: "订阅链接"
    # <<: *dy
    # path: ./provide/保存到本地文件名.yaml
    # override:
      # additional-prefix: "代理提供商 | "

item: &p
  type: select
  proxies:
    - 默认🌺
    - 备用❤️
    - 备用🧡
    - 备用💛
    - 备用💚
    - 备用💙
    - 备用💜
    - 专线
    - 台湾
    - 香港
    - 自动选择
    - 负载均衡
    - 故障排除
    - DIRECT
    - REJECT

d: &d
  type: select
  include-all: true

proxy-groups:
  # 代理
  - name: 默认🌺
    type: select
    proxies:
      - 备用❤️
      - 备用🧡
      - 备用💛
      - 备用💚
      - 备用💙
      - 备用💜
      - 专线
      - 台湾
      - 香港
      - 自动选择
      - 负载均衡
      - 故障排除
      - DIRECT
      - REJECT
  - name: 备用❤️
    <<: *d
  - name: 备用🧡
    <<: *d
  - name: 备用💛
    <<: *d
  - name: 备用💚
    <<: *d
  - name: 备用💙
    <<: *d
  - name: 备用💜
    <<: *d
  - name: 专线
    <<: *d
    filter: '专线'
  - name: 台湾
    <<: *d
    filter: '台湾|Taiwan|TW|tw'
  - name: 香港
    <<: *d
    filter: '香港|Hong Kong|HK|hk'

    # type 可以是：
    # select（手动选择）
    # url-test（测速后自动选择最快）
    # fallback（主节点失效自动切换）
    # load-balance（负载均衡）

  - name: 故障排除
    type: fallback
    <<: *q
    # include-all: true
    use:
      - jk

  - name: 负载均衡
    type: load-balance
    <<: *q
    # include-all: true
    use:
      - zmdy
      - tsmeow
    strategy: round-robin # consistent-hashing
    # 浏览网页或下载：round-robin
    # 游戏或登录敏感：consistent-hashing

  - name: 自动选择
    type: url-test
    <<: *q
    # include-all: true
    use:
      - zmdy
      - jk
    tolerance: 150 # RTT 容忍值（毫秒）

  # 策略
  - name: Steam
    <<: *p
  - name: ChatGpt
    <<: *p
  - name: Google
    <<: *p
  - name: Telegram
    <<: *p
  - name: Twitter
    <<: *p
  - name: YouTube
    <<: *p
  - name: Github
    <<: *p
  - name: Instagram
    <<: *p
  # - name: 哔哩哔哩
    # <<: *p
  - name: 国内
    <<: *p

    # type: select
    # proxies:
      # - DIRECT
    # hidden: true
rule: &rp
  type: http
  behavior: classical
  format: yaml
  interval: 86400
rule-providers:
  直连规则:
    <<: *rp
    path: ./rule_providers/直连规则.yaml
    url: "https://raw.githubusercontent.com/moexiyuki/mihomo-config-hub/1e12c0b892f3946d011031946939d17ddfe06c12/rule_direct.yaml"
    
  秋风广告规则:
    <<: *rp
    path: ./rule_providers/秋风广告规则.yaml
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml"

rules:
  # 直连局域网流量
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - GEOIP,private,DIRECT,no-resolve

  - IP-CIDR,1.1.1.1/32,默认🌺,no-resolve
  - IP-CIDR,8.8.8.8/32,默认🌺,no-resolve
  # FCM
  - GEOSITE,googlefcm,DIRECT
  # 广告过滤
  - RULE-SET,秋风广告规则,REJECT
  # - RULE-SET,直连规则,DIRECT

  # Steam
  - DOMAIN,store.steampowered.com,Steam
  - DOMAIN,api.steampowered.com,Steam
  - DOMAIN,help.steampowered.com,Steam
  - DOMAIN,partner.steampowered.com,Steam
  - DOMAIN,checkout.steampowered.com,Steam
  - DOMAIN,community.steamcommunity.com,Steam
  - DOMAIN,steamcommunity.com,Steam
  - DOMAIN,steampowered.com,Steam
  - DOMAIN,steam-chat.com,Steam
  - DOMAIN,steamusercontent.com,Steam
  - DOMAIN-SUFFIX,steamstatic.com,Steam
  - DOMAIN-SUFFIX,steamgames.com,Steam
  - DOMAIN-SUFFIX,steamcontent.com,Steam
  - DOMAIN-SUFFIX,steamserver.net,Steam

  - DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
  - DOMAIN-SUFFIX,steamcontent.com,DIRECT
  - DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,DIRECT
  - DOMAIN-SUFFIX,steam.apac.qtlglb.com,DIRECT
  - DOMAIN-SUFFIX,steam.cdn.on.net,DIRECT
  - DOMAIN-SUFFIX,steam.naeu.qtlglb.com,DIRECT
  - DOMAIN-SUFFIX,steam.ix.asn.au,DIRECT
  - DOMAIN-SUFFIX,cdn.steampipe.steamcontent.com,DIRECT
  - DOMAIN-SUFFIX,hsar.steampowered.com.edgesuite.net,DIRECT
  - DOMAIN-SUFFIX,edgecast.steamstatic.com,DIRECT
  - DOMAIN-SUFFIX,fastly.steamstatic.com,DIRECT

  - DOMAIN-SUFFIX,steamserver.net,DIRECT
  - DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
  - DOMAIN-SUFFIX,steamchina.com,DIRECT

  - GEOSITE,steam,Steam

  # 国外
  - GEOSITE,instagram,Instagram
  - GEOSITE,openai,ChatGpt
  - GEOSITE,github,Github
  - GEOSITE,twitter,Twitter
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,telegram,Telegram
  - GEOSITE,cloudflare,默认🌺
  # b站
  # - GEOSITE,bilibili,DIRECT

  # GEOIP 防止纯 IP 流量漏网
  - GEOIP,twitter,Twitter,no-resolve
  - GEOIP,google,Google,no-resolve
  - GEOIP,telegram,Telegram,no-resolve
  - GEOIP,cloudflare,默认🌺,no-resolve
  # 国内
  - DOMAIN-SUFFIX,cn,国内
  # - DOMAIN-KEYWORD,-cn,国内
  - GEOSITE,geolocation-cn,国内
  - GEOIP,CN,国内,no-resolve
  # 兜底
  # - GEOSITE,geolocation-!cn,默认🌺
  - MATCH,默认🌺
